version: '3.7'

services:
  amq:
    image: vromero/activemq-artemis:latest-alpine
#    container_name: activemq
    environment:
      ARTEMIS_USERNAME: user
      ARTEMIS_PASSWORD: password
    ports:
      - 8161:8161
      - 61616:61616