server:
  port: 8080
  servlet:
    context-path: /hr
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: para-testar
  datasource:
    username: root
    password: admin
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console


    hikari:
      connection-timeout: 30000
      #      idle-timeout: 600000
      #      max-lifetime: 1800000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  activemq:
    user: user
    password: password
    broker-url: tcp://localhost:61616

queue:
  person: dataperson

url.viacep: https://viacep.com.br/ws/{cepNumber}/json/